apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/foundations
commonAnnotations:
  fulfillflow.io/validation-only: 'true'
  fulfillflow.io/deployment-blocked: environment-and-image-provenance-not-approved
patches:
- target:
    kind: StatefulSet
  patch: '[{"op": "add", "path": "/spec/template/spec/nodeSelector", "value": {"fulfillflow.io/deployment-approved":
    "example-never-schedule"}}]'
